# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       input-event-daemon

# >> macros
# << macros

Summary:    Streams input events from network to uinput device
Version:    0.0.0
Release:    1
Group:      System/Packages
License:    LGPLv2
URL:        https://github.com/jhakonen/input-event-daemon
Source0:    %{name}-%{version}.tar.bz2
Source100:  input-event-daemon.yaml
Requires:   systemd
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Network)

%description
The daemon streams e.g. keyboard events it receives from network connection to a uinput device. This allows emulation of hardware keys in the emulator.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
mkdir -p %{buildroot}%{_unitdir}/multi-user.target.wants
ln -sf ../input-event-daemon.service %{buildroot}%{_unitdir}/multi-user.target.wants/
# << install post

%preun
# >> preun
if [ "$1" -eq 0 ]; then
systemctl stop input-event-daemon.service
fi
# << preun

%post
# >> post
systemctl daemon-reload
systemctl reload-or-try-restart input-event-daemon.service
# << post

%postun
# >> postun
systemctl daemon-reload
# << postun

%files
%defattr(-,root,root,-)
%{_bindir}/input-event-daemon
%{_unitdir}/input-event-daemon.service
%{_unitdir}/multi-user.target.wants/input-event-daemon.service
# >> files
# << files
